import {morningBriefProse, isMarketSetupHeading} from './morningBriefPresentation'
import { briefHeadline, cleanObservedPrefixes, macroProse } from './briefPresentation'
import {useEffect,useMemo,useState} from 'react'
import OwnerApp, {isDashboardData, normalizeDashboardData, DailyBriefTimeline, LatestMarketContextEvidence, CioBrief, ValuationDashboard, TradingViewSymbolOverview, type DashboardData} from './App'
import {useMarketData,isStagedPreviewBuild} from './useMarketData'
import {WorkflowOps} from './WorkflowOps'
import {hasPublicationContract} from './publicationValidation'
import {siteConfig} from './siteConfig'
export const isPublicMarketsData = (value: unknown): value is DashboardData => isDashboardData(value) && hasPublicationContract(value)
import {ThemeControl} from './theme'
import {Narrative,ResearchHeadline,Quote,Ticker,Status,SourceLink,ThesisUpdate,formatTimestamp,type KnownSymbols} from './researchComponents'
import {filterResearch,researchCategoryCounts,publicRoute,type CompanyRow,type Publication} from './publicationTypes'

function CompanyChart({symbol,exchange,tradingViewSymbol}:{symbol:string;exchange?:string;tradingViewSymbol?:string}) {return <section className="markets-section"><h2>Price history</h2><p>External chart from TradingView. Prices may be delayed; chart availability varies by exchange.</p><TradingViewSymbolOverview symbols={[{symbol,exchange,tradingViewSymbol}]} title="Historical price" height={380}/></section>}
function Dates({item}:{item:Publication}) {return <p className="markets-metadata">{item.publishedAt||item.publishedDate ? `Published ${formatTimestamp(item.publishedAt||item.publishedDate)}` : 'Publication date unavailable'} · {item.informationAt||item.informationDate ? `Information updated ${formatTimestamp(item.informationAt||item.informationDate)}` : 'Information update date unavailable'}</p>}
export function PublicationArticle({item,symbols,lead=false}:{item:Publication;symbols:KnownSymbols;lead?:boolean}) {
 const macro = item.jobId === 'synthetic-macro' || item.title.trim().toLowerCase() === 'macro read';
 const morning = item.jobId === 'synthetic-morning' || item.title.trim().toLowerCase() === 'morning market briefing';
 const prose = (text: string) => macro ? macroProse(text) : morning ? morningBriefProse(cleanObservedPrefixes(text)) : cleanObservedPrefixes(text);
 const title = briefHeadline(item.title);
 const weekly = ['synthetic-job-08', 'synthetic-job-0c'].includes(item.jobId);
 const label = weekly ? <p className="markets-metadata">Weekly Stock Analysis</p> : null;
 const sources=(ids:string[]=[])=>item.sources.filter(s=>ids.includes(s.id)).map(s=><SourceLink key={s.id} label={s.title} url={s.url}/>);
 if(lead) return <article className="markets-lead" data-publication-id={item.id} data-content-type={item.type}>{label}<Dates item={item}/>{title && <h1><ResearchHeadline content={title} knownSymbols={symbols}/></h1>}{item.summary!==item.title&&<Narrative content={prose(item.summary)} knownSymbols={symbols}/>}<a href={`#briefs/${encodeURIComponent(item.id)}`}>Read full article →</a></article>;
 return <article className={lead?'markets-lead':'markets-publication'} data-publication-id={item.id} data-content-type={item.type}>
 {label}<Dates item={item}/>{title && <h1><ResearchHeadline content={title} knownSymbols={symbols}/></h1>}{item.summary!==item.title&&<Narrative content={prose(item.summary)} knownSymbols={symbols}/>}
 {item.assessment&&<Status value={item.assessment}/>}{item.quote&&<Quote quote={item.quote} trusted/>}
 {item.action&&<section className="markets-section"><h2>Current view</h2><Narrative content={item.action.currentView} knownSymbols={symbols}/><h3>Why</h3><Narrative content={item.action.why} knownSymbols={symbols}/>{item.action.prerequisites.length>0&&<><h3>What would change the view</h3><ul>{item.action.prerequisites.map(v=><li key={v}><Narrative content={v} knownSymbols={symbols}/></li>)}</ul></>}{item.action.horizon&&<p>Time horizon: {item.action.horizon}</p>}{item.action.context&&<p>{item.action.context}</p>}{item.action.mainRisk&&<><h3>Main risk</h3><Narrative content={item.action.mainRisk} knownSymbols={symbols}/></>}{sources(item.action.sourceIds)}</section>}
 {item.sections.map((section,i)=><section className="markets-section" key={i}>{!(morning && isMarketSetupHeading(section.heading)) && <h2>{section.emoji&&!section.heading.startsWith(section.emoji)?`${section.emoji} `:''}{section.heading}</h2>}<Narrative content={prose(section.markdown)} knownSymbols={symbols}/><div className="markets-source-links">{sources(section.sourceIds)}</div></section>)}
 {!!item.thesisHistory?.length&&<section className="markets-section"><h2>Research history</h2>{item.thesisHistory.map((h,i)=><ThesisUpdate key={i} previousView={h.previousView} newEvidence={h.evidence} currentView={h.currentView} date={h.informationAt} knownSymbols={symbols} sources={item.sources.filter(s=>h.sourceIds.includes(s.id)).map(s=>({label:s.title,url:s.url}))}/>)}</section>}
 {!!item.sources.length&&<section className="markets-section"><h2>Sources</h2><ul>{item.sources.map(s=><li key={s.id}><SourceLink label={s.title} url={s.url}/></li>)}</ul></section>}
 </article>
}
export function ResearchDirectory({rows,publications,symbols}:{rows:CompanyRow[];publications:Publication[];symbols:KnownSymbols}) {
 const [search,setSearch]=useState(''),[theme,setTheme]=useState(''),[assessment,setAssessment]=useState('');
 const visible=filterResearch(rows,search,theme,assessment,publications);
 const categoryCounts=researchCategoryCounts(rows,search,assessment,publications);
 const themes=[...new Set(rows.map(r=>r.category).filter(Boolean))].sort();
 const assessments=[...new Set(publications.filter(p=>p.type==='company').map(p=>p.assessment).filter((s):s is string=>!!s))].sort();
 return <section><h1>Company research</h1><p>Explore the evidence, risks, and changes behind each company’s research.</p><p className="markets-metadata" id="category-count-help">Company counts reflect your search and research-stance filters.</p><div className="markets-category-grid" aria-label="Research categories" aria-describedby="category-count-help"><button type="button" aria-pressed={!theme} onClick={()=>setTheme('')}>All companies <span>{categoryCounts.get('')||0}</span></button>{themes.map(category=><button type="button" key={category} aria-pressed={theme===category} onClick={()=>setTheme(category)}>{category} <span>{categoryCounts.get(category)||0}</span></button>)}</div><div className="markets-filters"><label>Search companies<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ticker or company"/></label><label>Theme<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="">All themes</option>{themes.map(t=><option key={t}>{t}</option>)}</select></label><label>Research stance<select value={assessment} onChange={e=>setAssessment(e.target.value)}><option value="">All assessments</option>{assessments.map(s=><option key={s}>{s}</option>)}</select></label><button onClick={()=>{setSearch('');setTheme('');setAssessment('')}}>Clear filters</button></div><p className="markets-metadata" aria-live="polite">{visible.length} companies</p><div className="markets-table-scroll"><table className="markets-research-table"><thead><tr><th>Company</th><th>Theme</th><th>Research stance</th><th>Latest research</th><th>Information updated</th></tr></thead><tbody>{visible.map(row=>{const publication=publications.find(p=>p.type==='company'&&p.tickers.includes(row.symbol));return <tr key={row.symbol}><td><Ticker symbol={row.symbol} companyName={row.title} href={`#research/${encodeURIComponent(row.symbol)}`}/></td><td>{row.category||'Not classified'}</td><td><Status value={publication?.assessment}/></td><td><Narrative content={publication?.summary||row.summary||'Research summary unavailable.'} knownSymbols={symbols}/></td><td>{formatTimestamp(publication?.informationAt||publication?.informationDate||row.updated)}</td></tr>})}</tbody></table></div>{!visible.length&&<p className="markets-empty">No companies match these filters. Clear filters to see all research.</p>}</section>
}
export default function MarketsApp(){
 const market=useMarketData(isPublicMarketsData);
 const data=useMemo(()=>normalizeDashboardData(market.data),[market.data]);
 const publications=((data as unknown as {publications?:Publication[]})?.publications||[]);
 const rows=(data?.tickers||[]) as CompanyRow[];
 const symbols=useMemo(()=>rows.map(r=>({symbol:r.symbol,companyName:r.title,href:`#research/${encodeURIComponent(r.symbol)}`})),[rows]);
 const [route,setRoute]=useState(()=>publicRoute(window.location.hash));
 const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{if(!menuOpen)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenuOpen(false);document.getElementById('markets-menu-toggle')?.focus()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[menuOpen]);
 useEffect(()=>{const change=()=>{setRoute(publicRoute(window.location.hash));setMenuOpen(false);window.scrollTo(0,0)};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[]);
 const briefs=publications.filter(p=>p.type==='brief').sort((a,b)=>(b.informationAt||b.informationDate||b.publishedAt||b.publishedDate||'').localeCompare(a.informationAt||a.informationDate||a.publishedAt||a.publishedDate||''));
 const themes=publications.filter(p=>p.type==='theme');
 const companies=publications.filter(p=>p.type==='company').sort((a,b)=>(b.informationAt||b.informationDate||b.publishedAt||b.publishedDate||'').localeCompare(a.informationAt||a.informationDate||a.publishedAt||a.publishedDate||''));
 const lead=briefs[0];
 const themeList=<div className="markets-theme-list">{themes.map(p=><article key={p.id}><h3><a href={`#themes/${encodeURIComponent(p.id)}`}>{p.title}</a></h3><Narrative content={p.summary} knownSymbols={symbols}/><Dates item={p}/></article>)}{!themes.length&&<p className="markets-empty">Thematic coverage is not available in this edition.</p>}</div>;
 let content;
 if(route.page==='about') content=<article className="markets-reading"><h1>About {siteConfig.name}</h1><p>{siteConfig.description}</p><h2>Research that can change its mind</h2><p>{siteConfig.name} brings together company research, market briefs, and thematic coverage. The aim is to explain what changed, distinguish evidence from interpretation, and make the sources easy to explore.</p><h2>How it is produced</h2><p>Hermes AI agents collect and synthesize research through scheduled publishing jobs. Reports may draw on company disclosures, financial data, and attributed commentary. AI can make errors or miss important context; publication does not mean that every item has been reviewed by a person.</p><h2>Reading the research</h2><p>Publication time and underlying information time are shown separately. Quotes are snapshots, not a live feed. Business outlook, valuation, and conditions for considering a purchase are distinct assessments. Missing or unresolved assessments are withheld rather than turned into a recommendation.</p><p>This is informational research, not personalized investment advice. Outcomes are uncertain and no performance is guaranteed. Check original sources before making investment decisions.</p><h2>Financial terms</h2><dl><dt>Free cash flow (FCF)</dt><dd>Cash generated after capital expenditure; definitions can vary by company.</dd><dt>EBITDA</dt><dd>Earnings before interest, taxes, depreciation, and amortization. It is not cash flow.</dd><dt>Return on invested capital (ROIC)</dt><dd>A measure of operating returns relative to the capital invested in a business.</dd><dt>Annual recurring revenue (ARR)</dt><dd>An annualized measure of recurring revenue, not necessarily recognized accounting revenue.</dd><dt>Remaining performance obligations (RPO)</dt><dd>Contracted revenue not yet recognized; timing and cancellation terms matter.</dd><dt>Stock-based compensation (SBC)</dt><dd>Employee compensation paid in equity, which can dilute shareholders.</dd><dt>Next twelve months (NTM)</dt><dd>A forward-looking estimate period, rather than a reported historical result.</dd><dt>Enterprise value (EV)</dt><dd>A measure of total business value including debt and subtracting cash, subject to methodology.</dd></dl><p>{siteConfig.attribution}</p></article>;
 else if(!data) content=<p role="status" className="markets-empty">{market.error?'Research is temporarily unavailable. Please try again later.':'Loading research…'}</p>;
 else if(route.page==='owner') content=<section className="markets-owner"><h1>Research workspace</h1><p>Additional analysis and source tools. Ticker research opens contextually from ticker links. This is a public workspace, not an authenticated private area.</p><OwnerApp/></section>;
 else if(route.page==='brief') content=<section className="markets-daily"><h1>Daily Brief</h1><DailyBriefTimeline data={data}/><LatestMarketContextEvidence data={data} onSelectTicker={symbol=>{window.location.hash=`research/${encodeURIComponent(symbol)}`}}/></section>;
 else if(route.page==='cio') content=<section className="markets-cio"><h1>Conviction List</h1><CioBrief data={data} onSelectTicker={symbol=>{window.location.hash=`research/${encodeURIComponent(symbol)}`}}/></section>;
 else if(route.page==='evaluation') content=<section className="markets-evaluation"><h1>Valuation</h1><ValuationDashboard data={data}/></section>;
 else if(route.page==='ops') content=<WorkflowOps data={data} mode={market.mode} isStagedPreview={isStagedPreviewBuild} lastCheckedAt={market.lastCheckedAt} manifest={market.manifest} error={market.error}/>;
 else if(route.page==='research') content=<ResearchDirectory rows={rows} publications={publications} symbols={symbols}/>;
 else if(route.page==='company') {const row=rows.find(r=>r.symbol===route.id);const item=companies.find(p=>p.tickers.includes(route.id||''));content=<section className="markets-company"><a href="#research">← All company research</a>{row&&<header><Ticker symbol={row.symbol} companyName={row.title}/></header>}{row&&<CompanyChart key={row.symbol} symbol={row.symbol} exchange={row.exchange} tradingViewSymbol={row.tradingViewSymbol}/>}{item?<PublicationArticle item={item} symbols={symbols}/>:row?<article><h1>{row.title}</h1><p className="markets-metadata">Information updated {formatTimestamp(row.updated)}</p><Status/><h2>Current thesis</h2><Narrative content={row.thesis||row.summary} knownSymbols={symbols}/>{row.risk&&<><h2>Risks</h2><Narrative content={row.risk} knownSymbols={symbols}/></>}{row.detailSections?.map((s,i)=><section className="markets-section" key={i}><h2>{s.title}</h2><Narrative content={s.summary} knownSymbols={symbols}/>{s.bullets?.map((v,j)=><Narrative key={j} content={v} knownSymbols={symbols}/>)}</section>)}</article>:<p className="markets-empty">Company research is not available for this symbol.</p>}{item&&row?.detailSections?.length ? <section className="markets-section"><h2>Financial information and further evidence</h2>{row.detailSections.map((section,i)=><details key={i}><summary>{section.title}</summary><Narrative content={section.summary} knownSymbols={symbols}/>{section.bullets?.map((text,j)=><Narrative key={j} content={text} knownSymbols={symbols}/>)}</details>)}</section>:null}</section>}
 else if(route.page==='publication') {const item=publications.find(p=>p.id===route.id);content=item?<PublicationArticle item={item} symbols={symbols}/>:<p className="markets-empty">This publication is not available in the current edition.</p>}
 else if(route.page==='themes') content=<section><h1>Themes</h1><p>Research across the businesses and forces shaping markets.</p>{themeList}</section>;
 else content=<><p className="markets-eyebrow">The market brief · AI-powered research</p>{lead?<PublicationArticle item={lead} symbols={symbols} lead/>:<section className="markets-lead"><h1>Evidence before conclusions</h1><p>The latest brief is not available in this edition. Explore the company research below.</p></section>}{lead?.thesisHistory?.length?<section className="markets-section"><h2>What changed</h2>{lead.thesisHistory.slice(0,3).map((h,i)=><ThesisUpdate key={i} previousView={h.previousView} newEvidence={h.evidence} currentView={h.currentView} date={h.informationAt} knownSymbols={symbols}/>)}</section>:null}<section className="markets-section"><h2>Themes in focus</h2>{themeList}</section>{briefs.length>1&&<section className="markets-section"><h2>Earlier briefs</h2>{briefs.slice(1).map(p=><article key={p.id}><h3><a href={`#briefs/${encodeURIComponent(p.id)}`}>{p.title}</a></h3><Dates item={p}/></article>)}</section>}</>;
 return <div className="markets-app"><a className="markets-skip-link" href="#markets-content">Skip to content</a><header className="markets-header"><a className="markets-brand" href="#brief"><strong>{siteConfig.name}</strong><span>{siteConfig.attribution}</span></a><button id="markets-menu-toggle" className="markets-menu-toggle" type="button" aria-expanded={menuOpen} aria-controls="markets-navigation-panel" aria-label={menuOpen?'Close navigation menu':'Open navigation menu'} onClick={()=>setMenuOpen(open=>!open)}><span aria-hidden="true">{menuOpen?'×':'☰'}</span> Menu</button><div id="markets-navigation-panel" className="markets-navigation-panel" data-open={menuOpen}><nav aria-label="Main navigation" className="markets-nav">{siteConfig.navigation.map(n=><a key={n.id} href={`#${n.id}`} onClick={()=>setMenuOpen(false)} aria-current={route.page===n.id||(n.id==='valuation'&&route.page==='evaluation')?'page':undefined}>{n.label}</a>)}</nav><ThemeControl/></div></header><main id="markets-content" className="markets-main">{isStagedPreviewBuild&&<p className="markets-metadata">SYNTHETIC DEMO · fictional data · original source timestamps retained</p>}{market.error&&data&&<p className="markets-notice" role="status">The latest update could not be loaded. Showing the available edition with its original timestamps.</p>}{content}</main><footer className="markets-footer"><p><strong>{siteConfig.name}</strong> · {siteConfig.attribution}</p><p>AI-powered research, not personalized investment advice. Quotes may be delayed.</p><a href="#about">Methodology & sources</a> · <a href="#briefs">Brief publications</a> · <a href="#owner">Research workspace</a></footer></div>
}
