from __future__ import annotations

from typing import Protocol, Any

from trading_execution.models import TradeIntent


class BrokerAdapter(Protocol):
    def health(self) -> dict[str, Any]: ...
    def preview_order(self, intent: TradeIntent) -> dict[str, Any]: ...
    def list_positions(self) -> list[dict[str, Any]]: ...
    def list_open_orders(self) -> list[dict[str, Any]]: ...
